package _const

const (
	NewsInfo_Field_Id                        = "id"
	NewsInfo_Field_Image_Id                  = "image_id"
	NewsInfo_Field_Article_Title             = "article_title"
	NewsInfo_Field_Article_Short_Title       = "article_short_title"
	NewsInfo_Field_Article_Regular_Title     = "article_regular_title"
	NewsInfo_Field_Article_From_Url          = "article_from_url"
	NewsInfo_Field_Article_From_Website_Id   = "article_from_website_id"
	NewsInfo_Field_Article_From_Website_Name = "article_from_website_name"
	NewsInfo_Field_Article_Source            = "article_source"
	NewsInfo_Field_Article_Source_Channel    = "article_source_channel"
	NewsInfo_Field_Article_Author            = "article_author"
	NewsInfo_Field_Article_Channel_Id        = "article_channel_id"
	NewsInfo_Field_Article_Channel_Name      = "article_channel_name"
	NewsInfo_Field_Article_Time              = "article_time"
	NewsInfo_Field_Article_Tags_Id           = "article_tags_id"
	NewsInfo_Field_Article_Tags_Name         = "article_tags_name"
	NewsInfo_Field_Article_Type_Id           = "article_type_id"
	NewsInfo_Field_Article_Type_Name         = "article_type_name"
	NewsInfo_Field_Article_Category_Id       = "article_category_id"
	NewsInfo_Field_Article_Category_Name     = "article_category_name"
	NewsInfo_Field_Article_Keywords          = "article_keywords"
	NewsInfo_Field_Article_Summary           = "article_summary"
	NewsInfo_Field_Article_Property          = "article_property"
	NewsInfo_Field_Article_Comments          = "article_comments"
	NewsInfo_Field_Article_Rating_Id         = "article_rating_id"
	NewsInfo_Field_Article_Rating_Name       = "article_rating_name"
	NewsInfo_Field_Importance_Ratings        = "importance_ratings"
	NewsInfo_Field_Cyclical_Id               = "cyclical_id"
	NewsInfo_Field_Cyclical_Name             = "cyclical_name"
	NewsInfo_Field_Data_Source_Id            = "data_source_id"
	NewsInfo_Field_Data_Source_Name          = "data_source_name"
	NewsInfo_Field_Block_Code                = "block_code"
	NewsInfo_Field_Block_Name                = "block_name"
	NewsInfo_Field_Block_Type                = "block_type"
	NewsInfo_Field_Security_Code             = "security_code"
	NewsInfo_Field_Security_Name             = "security_name"
	NewsInfo_Field_Theme_Id                  = "theme_id"
	NewsInfo_Field_Theme_Name                = "theme_name"
	NewsInfo_Field_Path_Locator              = "path_locator"
	NewsInfo_Field_Priority                  = "priority"
	NewsInfo_Field_Source_News_Id            = "source_news_id"
	NewsInfo_Field_Publish_Time              = "publish_time"
	NewsInfo_Field_Status                    = "status"
	NewsInfo_Field_Is_Deliver                = "is_deliver"
	NewsInfo_Field_Is_Checked                = "is_checked"
	NewsInfo_Field_Is_Valid                  = "is_valid"
	NewsInfo_Field_Is_Broadcast              = "is_broadcast"
	NewsInfo_Field_Is_Sync_File              = "is_sync_file"
	NewsInfo_Field_Creator                   = "creator"
	NewsInfo_Field_Editor                    = "editor"
	NewsInfo_Field_Author                    = "author"
	NewsInfo_Field_Comments                  = "comments"
	NewsInfo_Field_Create_Time               = "create_time"
	NewsInfo_Field_Modify_Time               = "modify_time"
	NewsInfo_Field_SyncRowVersion            = "SyncRowVersion"
	NewsInfo_Field_Is_Top                    = "is_top"
	NewsInfo_Field_Bespeak_Status            = "bespeak_status"
	NewsInfo_Field_Bespeak_Time              = "bespeak_time"
	NewsInfo_Field_Upload_Cloud_Status       = "upload_cloud_status"
	NewsInfo_Field_NewsTags                  = "NewsTags"
	NewsInfo_Field_NewsTagsID                = "NewsTagsID"
	NewsInfo_Field_DataUrl                   = "data_url"

	//数据库同步创建时间
	NewsInfo_Field_SyncCreateTime = "Sync_CreateTime"
	//数据库同步最后更新时间
	NewsInfo_Field_SyncModifyTime = "Sync_ModifyTime"
)
